# Generated by Django 5.2.11 on 2026-03-06 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_remove_feed_like_count_remove_feed_profile_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='like_count',
            field=models.IntegerField(default=0),
        ),
    ]
