# Generated by Django 5.2.11 on 2026-03-07 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_bookmark_like_reply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='like_count',
        ),
    ]
